- name: check ~/.docker/config.json existence
  stat:
    path: ~/.docker/config.json
  register: docker_config_json_stat

# To avoid docker ERROR [internal] load metadata for <image url>
# https://stackoverflow.com/questions/66912085/why-is-docker-compose-failing-with-error-internal-load-metadata-suddenly
# https://stackoverflow.com/a/76577464/429162

- name: ensure ~/.docker/config.json has no credsStore key
  when: docker_config_json_stat.stat.exists
  vars:
    docker_config_dict: "{{ lookup('file', '~/.docker/config.json') }}"
  block:
    - name: Adjust content of ~/.docker/config.json
      when: "'credsStore' in docker_config_dict"
      copy:
        dest: ~/.docker/config.json
        content: "{{ docker_config_dict | ansible.utils.remove_keys('credsStore') | to_nice_json }}"
