python_build_deps: # https://github.com/danhper/asdf-python/issues/115:
  - build-essential  # to get c compiler
  
  - libffi-dev 
  - libncurses5-dev 
  - zlib1g 
  - zlib1g-dev 
  - libssl-dev

  - libreadline-dev 
  - libbz2-dev 
  - libsqlite3-dev

  - liblzma-dev  # https://stackoverflow.com/questions/57743230/userwarning-could-not-import-the-lzma-module-your-installed-python-is-incomple
  - lzma  # I needed this for python 3.11.4