# TODO evaluate https://docs.ansible.com/ansible/latest/collections/ansible/builtin/package_module.html
- name: install using apt
  apt:
    name: "{{ package }}"
    state: present
  become: true
  when: not skip_package_install