# check if go is already installed
- name: check if go is already installed
  shell: bash -lc "go version"
  register: go_version_run_result
  failed_when: false
  changed_when: false

- debug:
    msg: "go version found: {{ go_version_run_result.stdout | default('') }}"

- name: install go
  when: go_version_run_result.rc != 0
  block:
    - name: get version info from go.dev
      uri:
        url: https://go.dev/dl/?mode=json
        return_content: yes
      register: go_version_info

    # https://stackoverflow.com/a/71850340/429162
    - name: determine latest go version
      when: version == ""
      set_fact:
        latest_go_version: "{{ go_version_info.json | first | json_query('version') }}"

    - debug:
        var: go_download_url

    - name: Collect info about downloaded go version
      set_fact:
        downloaded_version_info: "{{ go_version_info.json | json_query('[*].files[?filename == `' + go_downloaded_filename + '`]') | first | first }}"
      
    - debug:
        var: downloaded_version_info

    - name: download go
      include_role:
        name: helpers/downloader
      vars:
        url: "{{ go_download_url }}"
        max_age_seconds: "{{ '1year' | community.general.to_seconds }}"
        checksum_algorithm: sha256
        expected_checksum: "{{ downloaded_version_info.sha256 }}"

    - debug:
        var: downloaded_checksum

    - name: ensure empty go install dir
      file:
        path: "{{ install_dir }}"
        state: "{{ item }}"
      with_items:
        - absent
        - directory

    - name: extract go
      unarchive:
        src: "{{ downloaded_path }}"
        dest: "{{ install_dir | dirname }}"
        copy: false

- name: ensure GO_PATH dir for user
  file:
    path: "{{ go_path }}"
    state: directory

# about GOROOT: https://go.dev/doc/manage-install
# about GOPATH: https://go.dev/doc/code
#	 https://stackoverflow.com/a/10847122/429162

- name: ensure go-specific envvars in ~/.profile (that is always sourced)
  blockinfile:
    path: ~/.profile
    marker: "# {mark} ANSIBLE MANAGED BLOCK - go"
    block: |
      export GOPATH="{{ go_path | expanduser }}:$GOPATH"
      export PATH="{{ go_path | expanduser }}/bin:{{ install_dir | expanduser }}/bin:$PATH"
      

- name: final go version
  when: go_version_run_result.rc != 0
  block:
    - name: final check of go version
      shell: bash -lc "go version"
      register: final_go_version_run_result
      changed_when: false

    - name: show final go version
      debug:
        msg: "final go version: {{ final_go_version_run_result.stdout }}"
