- name: debug
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/wsl.yaml
  vars:
    # skip_package_install: true
  roles:
    - role: tools/python_poetry
      vars:
        version: 1.4.1
  tasks:
