- name: debug
  hosts: localhost
  gather_facts: false
  vars:
    ansible_become_password: "{{ lookup('env', 'ANSIBLE_BECOME_PASSWORD') }}"
  roles:
    - tools/basics
  tasks:
    - name: install basic tools
      include_role:
        name: helpers/apt
      vars:
        packages: "{{ basic_packages }}"