- name: debug
  hosts: localhost
  gather_facts: true
  vars_files:
    - vars/wsl.yaml
    - vars/user_config.yaml
  vars:
    # skip_package_install: true
  roles:
    - role: helpers/pipx
      vars:
        name: toml-cli
  tasks:
