- name: debug
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/wsl.yaml
  vars:
    skip_package_install: true
  roles:
    - role: tools/pip
      vars:
        symlinked_pip_conf_path: "{{ windows_user_dir }}/pip/pip.ini"
