- name: wsl
  hosts: localhost
  gather_facts: false
  vars:
    ansible_become_password: "{{ lookup('env', 'ANSIBLE_BECOME_PASSWORD') }}"
    package_installer_role: helpers/apt
  roles:
    - unix/hushlogin
    - tools/basics
    - tools/pyenv
