- name: wsl
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/wsl.yaml
  roles:
    - unix/hushlogin
    - tools/basics
    - tools/pyenv
    
    - role: tools/pip
      vars:
        symlinked_pip_conf_path: "{{ windows_user_dir }}/pip/pip.ini"
    
    - role: tools/python_poetry
      vars:
        version: 1.4.1

    - role: tools/ssh
      vars:
        symlinked_ssh_dir: "{{ windows_user_dir }}/.ssh"
        added_to_keychain:
          - id_ed25519
          - id_ed25519_bitbucketcloud
