AutoThemeSwitchingEnabled: true
Autostart:
  Validate: true
AppsSwitch:
  Enabled: true
  Component:
    Mode: Switch
SystemSwitch:
  Enabled: true
  Component:
    Mode: Switch
    TaskbarColorOnAdaptive: false
    TaskbarColorWhenNonAdaptive: Light
    DWMPrevalenceSwitch: false
    DWMPrevalenceEnableTheme: Light
ColorFilterSwitch:
  Enabled: false
OfficeSwitch:
  # we do this using the registry, see tools\MsOfficeConfig.ps1
  Enabled: false
Location:
  Enabled: true
  SunsetOffsetMin: -60
  SunriseOffsetMin: 120
  CustomLat: 47.285561000000001
  CustomLon: 7.9475899999999999
Tunable:
  DisableEnergySaverOnThemeSwitch: false
  UseLogonTask: false
  ShowTrayIcon: true
  UICulture: en
Events:
  DarkThemeOnBattery: false
  Win10AllowLockscreenSwitch: true
Notifications:
  OnAutoThemeSwitching: true
  OnSkipNextSwitch: true
AutoSwitchNotify:
  Enabled: true
  GracePeriodMinutes: 1
Hotkeys:
  Enabled: true
  ToggleTheme: Ctrl + D8
Updater:
  AutoInstall: true
  Enabled: true
  Silent: false
  DaysBetweenUpdateCheck: 7
  CheckOnStart: false
